### ISSUE TITLE
Is this a MS Word Document in this repo with that docx suffix?

### ISSUE THREAD

**Issue by COLABORATI** [AmitKulkarni9/AutomatedSecurityTesting_OwaspZapPythonAPI#1]
A ms word document in a "security" context always looks a little bit awkward to the point one might reckon this could be kind of a satirical art project... if this is a serious effort, however, then you should definitely not put word documents in a git repo - better write some markdown or use one of the many open source documentation tools, like e.g. sphinx, or just use a simple static site generator.

People will just not take you seriously with publishing a word doc in a git repo. You will get much more attention for your project with a better accessible text format - just look at other projects here and learn how they do documentation.

Thanks for your attention!

**Comment by AmitKulkarni9** [comment]
Thanks, I will fix that :)
